#!/usr/bin/python

import sys
import onkyo


def usage():
    print "Usage:"

if __name__ == "__main__":
    if not len(sys.argv) > 1:
        usage()
    else:
        oky = onkyo.Onkyo()
        oky.connect()
        cmd = sys.argv[1]
        if cmd == "z2off":
            oky.z2off()
        elif cmd == "z2on":
            oky.z2power()
        elif cmd == "state":
            oky.printState()
        else:
            usage()
        oky.close()


