#!/usr/bin/python

import onkyo


def usage():
    pass

if __name__ == "__main__":
    if not len(sys.argv) > 2:
        usage()
    else:
        onkyo = onkyo.OnkyoTCP()
        cmd = sys.argv[1]
        if cmd == "z2off":
            onkyo.z2off()
        elif cmd == "z2on":
            onkyo.z2power()
        else:
            usage()


