#!/usr/bin/python

import sys
import onkyo


def usage():
    pass

if __name__ == "__main__":
    if not len(sys.argv) > 2:
        usage()
    else:
        oky = onkyo.Onkyo()
        cmd = sys.argv[1]
        if cmd == "z2off":
            oky.z2off()
        elif cmd == "z2on":
            oky.z2power()
        else:
            usage()


